#!/usr/bin/env python3
"""Generate the deterministic Stage 2F compile-time profile include.

The production profile is deliberately an input to this tool, never a
runtime register write.  The generated include contains only constants and
provenance so that RTL and review evidence have one source of authority.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCHEMA = ROOT / "spec/stage2f_adc_source_profile.schema.json"
DEFAULT_OUTPUT = ROOT / "rtl/generated/stage2f_adc_source_profile.svh"
ENCODING_CODES = {
    "UNKNOWN": 0,
    "UNSIGNED_WITH_ZERO_CODE": 1,
    "TWOS_COMPLEMENT": 2,
}
POLARITY_NEGATIVE = {
    "UNKNOWN": 0,
    "INCREASING_CODE_IS_POSITIVE": 0,
    "INCREASING_CODE_IS_NEGATIVE": 1,
}


def _unique_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def _load_json(path: Path) -> tuple[dict[str, Any], bytes]:
    raw = path.read_bytes()
    try:
        value = json.loads(raw.decode("utf-8"), object_pairs_hook=_unique_object)
    except (UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
        raise ValueError(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ValueError(f"profile/schema root must be an object: {path}")
    return value, raw


def _validate_schema_shape(schema: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    if schema.get("$schema") != "https://json-schema.org/draft/2020-12/schema":
        errors.append("schema must declare JSON Schema draft 2020-12")
    if schema.get("type") != "object" or schema.get("additionalProperties") is not False:
        errors.append("schema must be a closed object")
    required = set(schema.get("required", []))
    properties = schema.get("properties")
    if not isinstance(properties, dict):
        errors.append("schema properties must be an object")
    elif required != set(properties):
        errors.append("schema required and property fields must match exactly")
    if not isinstance(schema.get("allOf"), list) or not schema["allOf"]:
        errors.append("schema must contain its conditional profile rules")
    return errors


def validate_profile(schema: dict[str, Any], profile: dict[str, Any]) -> None:
    """Validate the profile against the repository's deliberately small schema."""

    # Importing the frozen validator keeps the generator aligned with the
    # audited schema subset without depending on a third-party package.
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from tools.stage2f_adc_contract_audit import validate_source_profile_contract

    errors = _validate_schema_shape(schema)
    errors.extend(validate_source_profile_contract(schema, profile))
    if profile.get("profile_state") == "CONFIGURED_DIGITAL" and profile.get(
        "profile_identity"
    ) == "UNCONFIGURED":
        errors.append("configured profile cannot use the reserved UNCONFIGURED identity")
    if errors:
        raise ValueError("profile validation failed: " + "; ".join(dict.fromkeys(errors)))


def render_include(schema_bytes: bytes, profile_bytes: bytes, profile: dict[str, Any]) -> str:
    encoding = str(profile["encoding"])
    zero_code = profile["zero_code"]
    if zero_code is None:
        zero_code = 0
    configured = int(profile["profile_state"] == "CONFIGURED_DIGITAL")
    ch1_negative = POLARITY_NEGATIVE[profile["channel_polarity"]["channel_1"]]
    ch2_negative = POLARITY_NEGATIVE[profile["channel_polarity"]["channel_2"]]
    profile_hash = hashlib.sha256(profile_bytes).hexdigest()
    schema_hash = hashlib.sha256(schema_bytes).hexdigest()
    identity = profile["profile_identity"]
    lines = [
        "// Generated by tools/generate_stage2f_adc_profile.py; do not edit.",
        "// Deterministic output: regenerate from the authoritative JSON profile.",
        f"// PROFILE_INPUT_SHA256={profile_hash}",
        f"// SCHEMA_INPUT_SHA256={schema_hash}",
        f"// PROFILE_IDENTITY={identity}",
        f"// PROFILE_STATE={profile['profile_state']}",
        f"// PROFILE_ENCODING={encoding}",
        f"// PROFILE_ZERO_CODE={zero_code}",
        "",
        "`ifndef STAGE2F_ADC_SOURCE_PROFILE_SVH",
        "`define STAGE2F_ADC_SOURCE_PROFILE_SVH",
        "`define STAGE2F_PROFILE_RAW_WIDTH 12",
        "`define STAGE2F_PROFILE_NORMALIZED_WIDTH 13",
        f"`define STAGE2F_PROFILE_CONFIGURED 1'b{configured}",
        f"`define STAGE2F_PROFILE_ENCODING 2'd{ENCODING_CODES[encoding]}",
        f"`define STAGE2F_PROFILE_ZERO_CODE 12'd{int(zero_code)}",
        f"`define STAGE2F_PROFILE_CH1_POLARITY_NEGATIVE 1'b{ch1_negative}",
        f"`define STAGE2F_PROFILE_CH2_POLARITY_NEGATIVE 1'b{ch2_negative}",
        f'`define STAGE2F_PROFILE_IDENTITY "{identity}"',
        f'`define STAGE2F_PROFILE_INPUT_SHA256 "{profile_hash}"',
        f'`define STAGE2F_PROFILE_SCHEMA_SHA256 "{schema_hash}"',
        "`endif",
        "",
    ]
    return "\n".join(lines)


def generate(schema_path: Path, profile_path: Path, output_path: Path, check: bool) -> bool:
    schema, schema_bytes = _load_json(schema_path)
    profile, profile_bytes = _load_json(profile_path)
    validate_profile(schema, profile)
    rendered = render_include(schema_bytes, profile_bytes, profile)
    if check:
        try:
            current = output_path.read_text(encoding="utf-8")
        except OSError:
            return False
        return current == rendered
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8", newline="\n")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--profile", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="verify output without writing")
    args = parser.parse_args(argv)
    try:
        ok = generate(
            args.schema.resolve(),
            args.profile.resolve(),
            args.output.resolve(),
            args.check,
        )
    except (OSError, ValueError, KeyError) as exc:
        print(f"STAGE2F_PROFILE_GENERATION=FAIL: {exc}", file=sys.stderr)
        return 1
    if args.check and not ok:
        print("STAGE2F_PROFILE_GENERATION_CHECK=FAIL", file=sys.stderr)
        return 1
    print("STAGE2F_PROFILE_GENERATION=PASS")
    print(f"PROFILE={args.profile.resolve()}")
    print(f"OUTPUT={args.output.resolve()}")
    print(f"MODE={'CHECK' if args.check else 'WRITE'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
